<?php
/**
 * Implements hook_xmlrpc().
 */
function yac_xmlrpc() {
  $methods[] =  array(
    'yac_drush_flush', // Method name.
    'yac_drush_flush', // Callback.
    array(
      'array', // Return variable.
      'array', // Input variable.
    ),
    t('XMLRPC callback to enable cache clear from Drush/CLI.'), // Description
  );

  return $methods;
}

/**
 * XMLRPC callback to enable cache clear from Drush/CLI.
 */
function yac_drush_flush($variables) {
  $cron_key = isset($variables['cron_key']) ? $variables['cron_key'] : NULL;
  $clears = isset($variables['clears']) ? $variables['clears'] : array();

  if (empty($cron_key) || variable_get('cron_key', 'drupal') != $cron_key) {
    watchdog('yac', 'yac could not flush cache(s) because an invalid key was used.', array(), WATCHDOG_ERROR);
    return array(
      'success' => FALSE,
      'message' => t('yac could not flush cache(s) because an invalid key was used.'),
    );
  }
  else {
    foreach ($clears as $bin => $cids) {
      $cache = _cache_get_object($bin);
      foreach ($cids as $serialized_cid => $wildcard) {
        $cache->clear(unserialize($serialized_cid), $wildcard);
      }
    }
    return array(
      'success' => TRUE,
      'message' => t('yac all requested flushes done.'),
    );
  }
}

/**
 * Implementation of hook_init().
 *
 * Used for displaying the yac stats for debug purposes.
 */
function yac_init() {
  global $user;

  if (($user->uid == 0) || !variable_get('yac_show_debug', FALSE)
      || !user_access('access yac statistics') || strstr($_SERVER['PHP_SELF'], 'update.php')
      || strstr($_GET['q'], 'autocomplete')) {
    return;
  }

  register_shutdown_function('yac_shutdown');
}

/**
 * @file
 * This integrates the drupal yac cache module.
 */

/**
 * Implementation of hook_permission().
 */
function yac_permission() {
  return array(
    'access yac statistics' =>  array(
      'title' => t('Access yac statistics'),
      'description' => t('Allows access to the statistics reports of yac.'),
    ),
  );
}

/**
 * See yac_init() which registers this function as a shutdown function.
 * Displays yac stats in the footer.
 */
function yac_shutdown() {
  global $yac_statistics;

  // Don't call theme() during shutdown if the registry has been rebuilt (such
  // as when enabling/disabling modules on admin/build/modules) as things break.
  // Instead, simply exit without displaying admin statistics for this page
  // load.  See http://drupal.org/node/616282 for discussion.
  if (!function_exists('theme_get_registry') || !theme_get_registry()) {
    return;
  }

  // Try not to break non-HTML pages.
  if (function_exists('drupal_get_http_header')) {
    $header = drupal_get_http_header('content-type');
    if ($header) {
      $formats = array('xml', 'javascript', 'json', 'plain', 'image', 'application', 'csv', 'x-comma-separated-values');
      foreach ($formats as $format) {
        if (strstr($header, $format)) {
          return;
        }
      }
    }
  }

  if (isset($yac_statistics) && is_array($yac_statistics)) {
    print '<div id="yac-devel"><h2>' . t('yac statistics') . '</h2>';
    $rows = array();

    foreach ($yac_statistics as $row) {
      if (is_array($row[2])) {
        $row[2] = implode(',<br />', $row[2]);
      }
      $rows[] = $row;
    }
    print theme('table', array(
      'header' => array(('Type'), t('Bin'), t('Cid(s)')),
      'rows' => $rows,
    ));
    print '</div>';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function yac_form_system_performance_settings_alter(&$form, $form_state) {
  $form['clear_cache']['clear']['#submit'][] = 'yac_flush_cache';

  $form['clear_cache']['yac'] = array(
    '#type' => 'submit',
    '#value' => t('Clear yac user cache'),
    '#submit' => array('yac_flush_cache'),
  );
}

/**
 * Helper function to clear user cache.
 */
function yac_flush_cache() {
  $yac = new Yac();

  if ($yac->flush()) {
    drupal_set_message(t('Cleared yac user cache.'));
  }
  else {
    drupal_set_message(t('Unable to clear yac user cache.'), 'error');
  }
}

